apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tb-http-loadbalancer
  namespace: thingsboard
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
spec:
  defaultBackend:
    service:
      name: tb-node
      port:
        number: 8080
  rules:
    - http:
        paths:
          # Close external access to prevent unauthorized use
          - path: /apiTrendz/system/signingKey/setup/anonymously
            pathType: Prefix
            backend:
              service:
                name: tb-web-ui
                port:
                  number: 8080
          - path: /analytics/actuator
            pathType: Prefix
            backend:
              service:
                name: tb-web-ui
                port:
                  number: 8080
          - path: /trendz/actuator
            pathType: Prefix
            backend:
              service:
                name: tb-web-ui
                port:
                  number: 8080
          # Allowed APIs for external access
          - path: /analytics/
            pathType: Prefix
            backend:
              service:
                name: trendz-app
                port:
                  number: 8888
          - path: /trendz/
            pathType: Prefix
            backend:
              service:
                name: trendz-app
                port:
                  number: 8888
          - path: /apiTrendz/
            pathType: Prefix
            backend:
              service:
                name: trendz-app
                port:
                  number: 8888
