apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tb-trendz-load-balancer
  namespace: thingsboard
  annotations:
    appgw.ingress.kubernetes.io/use-regex: 'true'
    kubernetes.io/ingress.class: azure/application-gateway
    appgw.ingress.kubernetes.io/request-timeout: "300"
    appgw.ingress.kubernetes.io/appgw-ssl-certificate: ThingsBoardHTTPCert
    appgw.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  rules:
    - http:
        paths:
          # Close external access to prevent unauthorized use
          - path: /apiTrendz/system/signingKey/setup/anonymously
            pathType: Prefix
            backend:
              service:
                name: tb-web-ui
                port:
                  number: 8080
          - path: /apiTrendz/system/signingKey/setup/anonymously
            pathType: Prefix
            backend:
              service:
                name: tb-web-ui
                port:
                  number: 8080
          - path: /analytics/actuator
            pathType: Prefix
            backend:
              service:
                name: tb-web-ui
                port:
                  number: 8080
          - path: /trendz/actuator
            pathType: Prefix
            backend:
              service:
                name: tb-web-ui
                port:
                  number: 8080
          # Allowed APIs for external access
          - path: /analytics/
            pathType: Prefix
            backend:
              service:
                name: trendz-app
                port:
                  number: 8888
          - path: /trendz/
            pathType: Prefix
            backend:
              service:
                name: trendz-app
                port:
                  number: 8888
          - path: /apiTrendz/
            pathType: Prefix
            backend:
              service:
                name: trendz-app
                port:
                  number: 8888

