apiVersion: v1
kind: Secret
metadata:
  name: logstash
  namespace: logging
type: Opaque
# WARN: DO NOT store unencrypted secret value in VCS (Git). Base64 is not an encryption. Take a look on SealedSecret or similar
stringData:
  ES_HOSTS: "https://elastic.your.domain:443"
  ES_USER: "elastic_username"
  ES_PASSWORD: "put__your__super__strong__password__here"
