apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: tb-http-loadbalancer
  namespace: thingsboard
spec:
  rules:
    - http:
        paths:
          # Close external access to prevent unauthorized use
          - path: /apiTrendz/system/signingKey/setup/anonymously
            pathType: Prefix
            backend:
              service:
                name: tb-web-ui
                port:
                  number: 8080
          - path: /analytics/actuator
            pathType: Prefix
            backend:
              service:
                name: tb-web-ui
                port:
                  number: 8080
          - path: /trendz/actuator
            pathType: Prefix
            backend:
              service:
                name: tb-web-ui
                port:
                  number: 8080
          # Allowed APIs for external access
          - path: /analytics/
            pathType: Prefix
            backend:
              service:
                name: trendz-app
                port:
                  number: 8888
          - path: /trendz/
            pathType: Prefix
            backend:
              service:
                name: trendz-app
                port:
                  number: 8888
          - path: /apiTrendz/
            pathType: Prefix
            backend:
              service:
                name: trendz-app
                port:
                  number: 8888

          - path: /api/v1/integrations/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: tb-integration-executor
                port:
                  name: http
          - path: /api/v1/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: tb-http-transport
                port:
                  number: 8080
          - path: /static/rulenode/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: tb-node
                port:
                  number: 8080
          - path: /static/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: tb-web-ui
                port:
                  number: 8080
          - path: /index.html
            pathType: ImplementationSpecific
            backend:
              service:
                name: tb-web-ui
                port:
                  number: 8080
          - path: /*
            pathType: ImplementationSpecific
            backend:
              service:
                name: tb-node
                port:
                  number: 8080